// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4GBdVunLowqtQk1rFPaTTcJDNYtqZ6fc',
    appId: '1:739982078213:web:a543a5c1c50f58221f876c',
    messagingSenderId: '739982078213',
    projectId: 'echo-vibes',
    authDomain: 'echo-vibes.firebaseapp.com',
    storageBucket: 'echo-vibes.appspot.com',
    measurementId: 'G-FE6WMJYBY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz3aOEKL7IrWSbUceTYGYm_9JLCWIdAWA',
    appId: '1:739982078213:android:c784ab9d7380fe971f876c',
    messagingSenderId: '739982078213',
    projectId: 'echo-vibes',
    storageBucket: 'echo-vibes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkIRVmBssYknBUhHrKYLfQNz2x1RK7sk0',
    appId: '1:739982078213:ios:ad6ba7f3337b64121f876c',
    messagingSenderId: '739982078213',
    projectId: 'echo-vibes',
    storageBucket: 'echo-vibes.appspot.com',
    iosBundleId: 'com.example.echovibes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkIRVmBssYknBUhHrKYLfQNz2x1RK7sk0',
    appId: '1:739982078213:ios:ad6ba7f3337b64121f876c',
    messagingSenderId: '739982078213',
    projectId: 'echo-vibes',
    storageBucket: 'echo-vibes.appspot.com',
    iosBundleId: 'com.example.echovibes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4GBdVunLowqtQk1rFPaTTcJDNYtqZ6fc',
    appId: '1:739982078213:web:9e6fd05fcd817dda1f876c',
    messagingSenderId: '739982078213',
    projectId: 'echo-vibes',
    authDomain: 'echo-vibes.firebaseapp.com',
    storageBucket: 'echo-vibes.appspot.com',
    measurementId: 'G-5VRMJ5V9KP',
  );
}
